backend:
  name: git-gateway
  branch: main

media_folder: "public/assets/upload"
public_folder: "assets/upload"

collections:
  - name: "event"
    label: "Event"
    folder: "src/events"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "imageURL", widget: "image" }
      - { label: "Start Date", name: "startDate", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["event"] }
      - { label: "Registration Link", name: "registrationLink", widget: "string" }
      - { label: "PDGA Link", name: "pdgaLink", widget: "string" }
      - { label: "Disc Golf Scene Link", name: "discGolfSceneEventLink", widget: "string" }
      - { label: "Info Link", name: "eventInfoLink", widget: "string" }
      - { label: "Results Link", name: "resultsLink", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "post"
    label: "Post"
    folder: "src/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
